service: subscribers

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    SERVERLESS: true

functions:
  app:
    handler: dist/app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline